{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":157334857,"authorName":"kevinmwalters","from":"&quot;kevinmwalters&quot; &lt;kwalters@...&gt;","profile":"kevinmwalters","replyTo":"LIST","senderId":"MmdXVh30joezXEwr-a-2CBmscDHKmzZQwIevb_fCxCxuDQ6-gQnScvXiFQ3-V7U4L7EBU_8j93KTn2f5KWCJZEMyc9sVYss-TAjAI_PR","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Re: Trouble building from cvs on os x 10.4.9","postDate":"1178651600","msgId":1624,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGYxcWk0ZyszcnQ2QGVHcm91cHMuY29tPg==","inReplyToHeader":"PEYxQTNCMzQ4LTc5RDctNDE4Mi05RDBFLTlGN0FBNTkyRDY5MkBjYWx0ZWNoLmVkdT4="},"prevInTopic":1623,"nextInTopic":0,"prevInTime":1623,"nextInTime":1625,"topicId":1622,"numMessagesInTopic":3,"msgSnippet":"Dave, Thanks for your response.  When I try something like: ... ___________________________________________ I don t have any problems, so it looks like using","rawEmail":"Return-Path: &lt;kwalters@...&gt;\r\nX-Sender: kwalters@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 27288 invoked from network); 8 May 2007 19:13:30 -0000\r\nReceived: from unknown (66.218.67.35)\n  by m44.grp.scd.yahoo.com with QMQP; 8 May 2007 19:13:30 -0000\r\nReceived: from unknown (HELO n5b.bullet.sp1.yahoo.com) (69.147.64.186)\n  by mta9.grp.scd.yahoo.com with SMTP; 8 May 2007 19:13:30 -0000\r\nReceived: from [216.252.122.219] by n5.bullet.sp1.yahoo.com with NNFMP; 08 May 2007 19:13:20 -0000\r\nReceived: from [66.218.69.1] by t4.bullet.sp1.yahoo.com with NNFMP; 08 May 2007 19:13:20 -0000\r\nReceived: from [66.218.66.79] by t1.bullet.scd.yahoo.com with NNFMP; 08 May 2007 19:13:20 -0000\r\nDate: Tue, 08 May 2007 19:13:20 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;f1qi4g+3rt6@...&gt;\r\nIn-Reply-To: &lt;F1A3B348-79D7-4182-9D0E-9F7AA592D692@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;kevinmwalters&quot; &lt;kwalters@...&gt;\r\nSubject: Re: Trouble building from cvs on os x 10.4.9\r\nX-Yahoo-Group-Post: member; u=157334857; y=oFbmiAZF_aa5DMBZr7a9-24hDYbQHbD7gBmN6qvZLR5bVHQXeCBksg\r\nX-Yahoo-Profile: kevinmwalters\r\n\r\nDave,\nThanks for your response.  When I try something like:\n_______________=\r\n____________________________\n&gt;&gt;&gt; gas =3D importPhase(&quot;gri30.xml&quot;,debug=3D1)=\r\n\n___________________________________________\n\nI don&#39;t have any problems, so=\r\n it looks like using .xml files works\njust fine.  \n\nIf the input is a .cti =\r\nfile, then the following happens:\n\n________________________________________=\r\n___\n&gt;&gt;&gt; gas =3D importPhase(&quot;frac.cti&quot;,debug=3D1)\n\n ct2ctml: executing the =\r\ncommand sleep 1; &quot;python&quot;\n&quot;./.cttmp1178651152.pyw&quot; &&gt; ./ct2ctml.log\nct2ctml=\r\n: the Python command is: python\nsleeping for 1 secs+\nct2ctml: retaining tem=\r\nporary file ./.cttmp1178651152.pyw\n\nTraceback (most recent call last):\n  Fi=\r\nle &quot;/Users/kevinwalters/code/ctcode/pydebug.py&quot;, line 2, in &lt;module&gt;\n    ga=\r\ns =3D importPhase(&quot;frac.cti&quot;,debug=3D1)\n  File\n&quot;/Library/Frameworks/Python.=\r\nframework/Versions/2.5/lib/python2.5/site-packages/Cantera/importFromFile.p=\r\ny&quot;,\nline 20, in importPhase\n    return importPhases(file, [name], loglevel,=\r\n debug)[0]\n  File\n&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/py=\r\nthon2.5/site-packages/Cantera/importFromFile.py&quot;,\nline 27, in importPhases\n=\r\n   \ns.append(solution.Solution(src=3Dfile,id=3Dnm,loglevel=3Dloglevel,debug=\r\n=3Ddebug))\n  File\n&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/py=\r\nthon2.5/site-packages/Cantera/solution.py&quot;,\nline 39, in __init__\n    prepro=\r\ncess =3D 1, debug =3D debug)\n  File\n&quot;/Library/Frameworks/Python.framework/V=\r\nersions/2.5/lib/python2.5/site-packages/Cantera/XML.py&quot;,\nline 35, in __init=\r\n__\n    self._xml_id =3D _cantera.xml_get_XML_File(src, debug)\nerror: \n\n****=\r\n********************************************\n                Cantera Error!=\r\n                  \n************************************************\n\n\nProce=\r\ndure: get_XML_File\nError:   cannot open ./frac.xml for reading.Note, this e=\r\nrror indicates\na possible configuration problem.\n__________________________=\r\n_________________\n\n\n\n\n--- In cantera@yahoogroups.com, David Goodwin &lt;dgoodw=\r\nin@...&gt; wrote:\n&gt;\n&gt; Kevin,\n&gt; \n&gt; Well, I did check in everything for version =\r\n1.7.1, but I haven&#39;t  \n&gt; announced that it is ready... so there may be some=\r\n small glitches  \n&gt; like you are finding that we need to fix. It is odd tho=\r\nugh, since I  \n&gt; use a powerbook configured much like yours and it works fi=\r\nne for me.   \n&gt; It seems to be some problem in finding data files. Try enab=\r\nling the  \n&gt; debug flag in importPhase:\n&gt; \n&gt; gas =3D importPhase(&quot;frac.cti&quot;=\r\n, debug =3D 1)\n&gt; \n&gt; This might tell you something.\n&gt; \n&gt; Dave\n&gt; \n&gt; \n&gt; On May=\r\n 8, 2007, at 9:17 AM, kevinmwalters wrote:\n&gt; \n&gt; &gt; I&#39;m having a little troub=\r\nle building Cantera 1.7.1 from cvs on my\n&gt; &gt; machine (PowerBook G4, ppc, OS=\r\nX 10.4.9, Python 2.5.1, numarray, gcc,\n&gt; &gt; sundials 2.3).\n&gt; &gt;\n&gt; &gt; Running t=\r\nhe &quot;preconfig&quot; script (unchanged), &quot;make&quot; and &quot;make install&quot;\n&gt; &gt; seems to g=\r\no fine without any warnings/errors.  However, when I run\n&gt; &gt; &quot;make test&quot;, o=\r\nr any script that uses importPhase, I get the following\n&gt; &gt; error...\n&gt; &gt; __=\r\n_________________________________\n&gt; &gt;\n&gt; &gt; Procedure: get_XML_File\n&gt; &gt; Error=\r\n:   cannot open ./diamond.xml for reading.Note, this error\n&gt; &gt; indicates a =\r\npossible configuration problem.\n&gt; &gt; Error opening up file1, diamond.csv\n&gt; &gt;=\r\n Traceback (most recent call last):\n&gt; &gt;   File &quot;frac.py&quot;, line 7, in &lt;modul=\r\ne&gt;\n&gt; &gt;     gas =3D importPhase(&#39;frac.cti&#39;)\n&gt; &gt;   File\n&gt; &gt; &quot;/Library/Framewo=\r\nrks/Python.framework/Versions/2.5/lib/python2.5/ \n&gt; &gt; site-packages/Cantera=\r\n/importFromFile.py&quot;,\n&gt; &gt; line 20, in importPhase\n&gt; &gt;     return importPhase=\r\ns(file, [name], loglevel, debug)[0]\n&gt; &gt;   File\n&gt; &gt; &quot;/Library/Frameworks/Pyt=\r\nhon.framework/Versions/2.5/lib/python2.5/ \n&gt; &gt; site-packages/Cantera/import=\r\nFromFile.py&quot;,\n&gt; &gt; line 27, in importPhases\n&gt; &gt;\n&gt; &gt; s.append(solution.Soluti=\r\non \n&gt; &gt; (src=3Dfile,id=3Dnm,loglevel=3Dloglevel,debug=3Ddebug))\n&gt; &gt;   File\n=\r\n&gt; &gt; &quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/ \n&gt; &gt; =\r\nsite-packages/Cantera/solution.py&quot;,\n&gt; &gt; line 39, in __init__\n&gt; &gt;     prepro=\r\ncess =3D 1, debug =3D debug)\n&gt; &gt;   File\n&gt; &gt; &quot;/Library/Frameworks/Python.fra=\r\nmework/Versions/2.5/lib/python2.5/ \n&gt; &gt; site-packages/Cantera/XML.py&quot;,\n&gt; &gt; =\r\nline 35, in __init__\n&gt; &gt;     self._xml_id =3D _cantera.xml_get_XML_File(src=\r\n, debug)\n&gt; &gt; cantera.error:\n&gt; &gt;\n&gt; &gt; ***************************************=\r\n*********\n&gt; &gt;                 Cantera Error!\n&gt; &gt; **************************=\r\n**********************\n&gt; &gt; ___________________________________\n&gt; &gt;\n&gt; &gt; Any =\r\nideas how to resolve this?  Is preconfig missing something?\n&gt; &gt;\n&gt; &gt; Thanks,=\r\n\n&gt; &gt;\n&gt; &gt; Kevin\n&gt; &gt;\n&gt; &gt;\n&gt; &gt;\n&gt; &gt;\n&gt; &gt; Yahoo! Groups Links\n&gt; &gt;\n&gt; &gt;\n&gt; &gt;\n&gt;\n\n\n\n"}}