{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":304378662,"authorName":"rustoleump","from":"&quot;rustoleump&quot; &lt;rustoleump@...&gt;","profile":"rustoleump","replyTo":"LIST","senderId":"eeN4hyzG2vkb4T8fTcB5jcWMecPvdAAbhimfEmIHQIFW7XjZUsGK2blYl2ML_oEjqfF2fRA1GTtaVA5ODm54K--tTql2BQ1a5AI","spamInfo":{"isSpam":false,"reason":"6"},"subject":"XML_TagMismatch","postDate":"1180239315","msgId":1664,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGYzYjBraitwa2o5QGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":0,"prevInTime":1663,"nextInTime":1665,"topicId":1664,"numMessagesInTopic":1,"msgSnippet":"I ve received the following error while trying to run a modified version of adiabatic_flame.py using a cti file that I generated (running on an iBook, 10.4.9, ","rawEmail":"Return-Path: &lt;rustoleump@...&gt;\r\nX-Sender: rustoleump@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 24491 invoked from network); 27 May 2007 04:15:57 -0000\r\nReceived: from unknown (66.218.66.167)\n  by m36.grp.scd.yahoo.com with QMQP; 27 May 2007 04:15:57 -0000\r\nReceived: from unknown (HELO n7c.bullet.sp1.yahoo.com) (69.147.64.167)\n  by mta6.grp.scd.yahoo.com with SMTP; 27 May 2007 04:15:57 -0000\r\nReceived: from [216.252.122.218] by n7.bullet.sp1.yahoo.com with NNFMP; 27 May 2007 04:15:15 -0000\r\nReceived: from [209.73.164.86] by t3.bullet.sp1.yahoo.com with NNFMP; 27 May 2007 04:15:15 -0000\r\nReceived: from [66.218.66.76] by t8.bullet.scd.yahoo.com with NNFMP; 27 May 2007 04:15:15 -0000\r\nDate: Sun, 27 May 2007 04:15:15 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;f3b0kj+pkj9@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;rustoleump&quot; &lt;rustoleump@...&gt;\r\nSubject: XML_TagMismatch\r\nX-Yahoo-Group-Post: member; u=304378662; y=sm9icx8PtChfq07dAzZM9-rF-_2Tr80OvP7M6-pBFvQDYNF9zA\r\nX-Yahoo-Profile: rustoleump\r\n\r\nI&#39;ve received the following error while trying to run a modified version of=\r\n \nadiabatic_flame.py using a cti file that I generated (running on an iBook=\r\n, 10.4.9, \nMacPython2.5):\n\nFile &quot;C2N2O.py&quot;, line 46, in &lt;module&gt;\n    gas =\r\n=3D IdealGasMix(rxnmech, mix)\n  File &quot;/Library/Frameworks/Python.framework/=\r\nVersions/2.5/lib/python2.5/site-\npackages/Cantera/gases.py&quot;, line 22, in Id=\r\nealGasMix\n    return Solution(src=3Dsrc,id=3Did,loglevel=3Dloglevel)\n  File=\r\n &quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-\npac=\r\nkages/Cantera/solution.py&quot;, line 39, in __init__\n    preprocess =3D 1, debu=\r\ng =3D debug)\n  File &quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/=\r\npython2.5/site-\npackages/Cantera/XML.py&quot;, line 35, in __init__\n    self._xm=\r\nl_id =3D _cantera.xml_get_XML_File(src, debug)\ncantera.error: \n\n***********=\r\n*************************************\n                Cantera Error!       =\r\n           \n************************************************\n\n\nProcedure: X=\r\nML_TagMismatch\nError:   Error in XML file at line 141.\n&lt;none&gt; paired with &lt;=\r\n/note&gt;.\n\nI found this in the .xml file:\n\nThis page contains the following e=\r\nrrors:\n\nerror on line 141 at column 1610: Opening and ending tag mismatch: =\r\nnone line 0 and \nnote\nBelow is a rendering of the page up to the first erro=\r\nr.\n\nThe data that follows goes through the first 4 species from the transpo=\r\nrt data file.  I had a \nproblem generating the cti file - ck2cti stated tha=\r\nt there were undeclared species in the \nreactions.  They were declared and =\r\nI modified the species list by increasing the spacing \nbetween species.  ck=\r\n2cti was then able to generate the cti file.\n\nI have search through the pos=\r\nts and not found anything that addresses this, although \nmessage 1461 is si=\r\nmilar.\n\nCan anyone point me in a direction to fix this problem? \nThanks.\nRu=\r\nsty  \n\n\n"}}