{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":44728387,"authorName":"David Goodwin","from":"David Goodwin &lt;dgoodwin@...&gt;","profile":"dggoodwin","replyTo":"LIST","senderId":"URX-_7AwA-Eee4a3jSAPTQL5BHcoppbPeglIhKDZp7EHcG0RNhOmX8GX7wz05Fcee7qZXgWchQ_nQM0QYGU9bmWmCmbsGVJn3jie","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Re: [cantera] python installation trouble","postDate":"1079384679","msgId":319,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDVGOUM0MjgwLTc2QzQtMTFEOC1CNDZFLTAwMDM5M0QyRDFBRUBjYWx0ZWNoLmVkdT4=","inReplyToHeader":"PGMzNHRzYis5N281QGVHcm91cHMuY29tPg==","referencesHeader":"PGMzNHRzYis5N281QGVHcm91cHMuY29tPg=="},"prevInTopic":318,"nextInTopic":329,"prevInTime":318,"nextInTime":320,"topicId":318,"numMessagesInTopic":3,"msgSnippet":"Ulf, Regarding the first error, it looks like it cannot find file gri30.cti. Note that a file .cttmp.py  is created that contains the commands that it was","rawEmail":"Return-Path: &lt;dgoodwin@...&gt;\r\nX-Sender: dgoodwin@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 78752 invoked from network); 15 Mar 2004 21:04:13 -0000\r\nReceived: from unknown (66.218.66.172)\n  by m3.grp.scd.yahoo.com with QMQP; 15 Mar 2004 21:04:13 -0000\r\nReceived: from unknown (HELO outgoing-mail.its.caltech.edu) (131.215.49.69)\n  by mta4.grp.scd.yahoo.com with SMTP; 15 Mar 2004 21:04:13 -0000\r\nReceived: from fire-dog (fire-dog [192.168.1.4])\n\tby earth-ox-postvirus (Postfix) with ESMTP id 6DA16109B09\n\tfor &lt;cantera@yahoogroups.com&gt;; Mon, 15 Mar 2004 13:04:13 -0800 (PST)\r\nReceived: from earth-ox ([192.168.1.9])\n\tby fire-dog (MailMonitor for SMTP v1.2.2 ) ;\n\tMon, 15 Mar 2004 13:04:12 -0800 (PST)\r\nReceived: from [192.168.1.101] (DHCP-101-166.caltech.edu [131.215.101.166])\n\tby earth-ox.its.caltech.edu (Postfix) with ESMTP id 64432109B09\n\tfor &lt;cantera@yahoogroups.com&gt;; Mon, 15 Mar 2004 13:04:12 -0800 (PST)\r\nMime-Version: 1.0 (Apple Message framework v612)\r\nIn-Reply-To: &lt;c34tsb+97o5@...&gt;\r\nReferences: &lt;c34tsb+97o5@...&gt;\r\nContent-Type: text/plain; charset=US-ASCII; format=flowed\r\nMessage-Id: &lt;5F9C4280-76C4-11D8-B46E-000393D2D1AE@...&gt;\r\nContent-Transfer-Encoding: 7bit\r\nDate: Mon, 15 Mar 2004 13:04:39 -0800\r\nTo: cantera@yahoogroups.com\r\nX-Mailer: Apple Mail (2.612)\r\nX-Spam-Status: No, hits=0.0 tagged_above=-100000.0 required=5.0 \r\nX-Spam-Level: \r\nX-eGroups-Remote-IP: 131.215.49.69\r\nFrom: David Goodwin &lt;dgoodwin@...&gt;\r\nSubject: Re: [cantera] python installation trouble\r\nX-Yahoo-Group-Post: member; u=44728387\r\nX-Yahoo-Profile: dggoodwin\r\n\r\nUlf,\n\nRegarding the first error, it looks like it cannot find file gri30.cti. \nNote that a file .cttmp.py  is created that contains the commands that \nit was trying to execute when it failed.\nSo try double-clicking on this file to run it, or at a command-line \nprompt in this directory type\n\npython .cttmp.py\n\nThe resulting error message will tell you what is wrong.  If it is not \nfinding gri30.cti, then one fix is to move this file (in the data \nfolder) into the folder where you are running the example.  If you are \ntrying to use Cantera on a machine running Windows 98 or Windows ME, \nthis problem is bound to occur, because the environment variable \nCOMMONPROGRAMFILES, which is supposed to be defined by the OS (and is \nin Windows XP and 2000), is not defined. On Windows PCs (only), Cantera \nuses this environment variable to look for where the data files are \ninstalled.  (This could probably be done better using the Registry, but \nI don&#39;t know how to do that and don&#39;t really want to learn... If anyone \nin the user&#39;s group has experience with accessing the Registry from \nC/C++, file &#39;misc.cpp&#39; in the Cantera C++ source code is where the \ndefault data directory locations are set.)\n\nAs far as the second error, the equilibrium routine now considers it an \nerror if the temperature goes outside the range for which the thermo \ndata are valid for all species. If you look in gri30.cti, you will see \nthat data for CH3O are only provided up to 3000 K.  When this range was \nexceeded, an error was flagged.  The way it is implemented in \nChemEquil.cpp has a problem, though, and will be changed. Currently if \nthe initial estimate is outside the range, this is considered an error. \nBut of course it should only be an error if the final converged value \nis outside the range.  The next  release will fix this.  The workaround \nis to change the upper temperature limit for CH3O.\n\nDave\n\n\nOn Mar 15, 2004, at 10:49 AM, usenechal wrote:\n\n&gt; Dear Prof. Goodwin,\n&gt;\n&gt; I just installed Cantera153.msi and tried the reactor1.py for testing\n&gt;  (I changed  I get an error :\n&gt;\n&gt; ------------start error message 1-----------------------------\n&gt; Traceback (most recent call last):\n&gt;   File &quot;C:&#92;Programme&#92;Cantera153&#92;demos&#92;Python&#92;reactor1.py&quot;, line 11, in \n&gt; ?\n&gt;     gri3 = GRI30()\n&gt;   File &quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;gases.py&quot;, line\n&gt; 33, in GRI30\n&gt;     return Solution(src=&quot;gri30.cti&quot;, id=&quot;gri30&quot;)\n&gt;   File &quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;solution.py&quot;,\n&gt; line 40, in __init__\n&gt;     root = XML.XML_Node(name = &#39;doc&#39;, src = src, preprocess = 1)\n&gt;   File &quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;XML.py&quot;, line\n&gt; 35, in __init__\n&gt;     self._xml_id = _cantera.xml_get_XML_File(src)\n&gt; error:\n&gt; Procedure: ct2ctml\n&gt; Error:   could not convert input file to CTML\n&gt;  command line was: c:/python23/python ./.cttmp.py&gt; ct2ctml.log 2&gt;&1\n&gt; Error in Python installation.\n&gt; ------------end error message 1-----------------------------\n&gt;\n&gt; When I modify the python-file to use\n&gt; &quot;gri3=IdealGasMix(&#39;gri30.xml&#39;,&#39;gri30&#39;)&quot; instead of &quot;gri3 = GRI30()&quot;\n&gt; the error changes to:\n&gt; ------------start error message 2-----------------------------\n&gt; Traceback (most recent call last):\n&gt;   File &quot;C:&#92;Programme&#92;Cantera153&#92;demos&#92;Python&#92;reactor1.py&quot;, line 15, in \n&gt; ?\n&gt;     gri3.equilibrate(&#39;HP&#39;)\n&gt;   File\n&gt; &quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;ThermoPhase.py&quot;, line\n&gt; 256, in equilibrate\n&gt;     _cantera.thermo_equil(self._phase_id, ixy)\n&gt; error:\n&gt; Procedure: ChemEquil\n&gt; Error:   Temperature (3028.9 K) outside valid range of 300 K to 3000 K\n&gt; ------------end error message 2-----------------------------\n&gt;\n&gt; This temperature seems to be wrong compared with former\n&gt; cantera-releases, so what are these errors ? Manually compiling\n&gt; cantera for python (with cygwin) gives the same result (with python\n&gt; for cygwin). Thanks a lot for your patience.\n&gt;\n&gt; best regards\n&gt; ulf\n&gt;\n&gt;\n&gt;\n&gt;\n&gt; Yahoo! Groups Links\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n\n\n\n"}}