{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":43678362,"authorName":"Mark Alexander Mikofski","from":"&quot;Mark Alexander Mikofski&quot; &lt;mikofski@...&gt;","profile":"bwanamarko","replyTo":"LIST","senderId":"5wXCxgiPSg38wQPtRdKhapv_e31W51g8_KnoTBbyKV2sUrfv7cASE4iVB3WZA8DLIeUQsT3HysFRD0Buk_Wcw5VHzujKs9J73wYmHH8aL6Bmqbw7xhzmfMvSOz7fHic","spamInfo":{"isSpam":false,"reason":"12"},"subject":"Re: ct2ctml problems?  (May not be a Cantera problem, though)","postDate":"1118427674","msgId":849,"canDelete":false,"contentTrasformed":false,"systemMessage":true,"headers":{"messageIdInHeader":"PGQ4Y2xtcStjZWt1QGVHcm91cHMuY29tPg==","inReplyToHeader":"PGQ1cDV2Zys5amtkQGVHcm91cHMuY29tPg=="},"prevInTopic":787,"nextInTopic":0,"prevInTime":848,"nextInTime":850,"topicId":785,"numMessagesInTopic":4,"msgSnippet":"Mark, I had the exact same problem. If you haven t already solve yours, try this: Delete the PYTHON_CMD variable you created, and only add c: Python24 to your","rawEmail":"Return-Path: &lt;mikofski@...&gt;\r\nReceived: (qmail 57074 invoked from network); 11 Jun 2005 01:59:55 -0000\r\nReceived: from unknown (66.218.66.166)\n  by m30.grp.scd.yahoo.com with QMQP; 11 Jun 2005 01:59:55 -0000\r\nReceived: from unknown (HELO n15a.bulk.scd.yahoo.com) (66.94.237.32)\n  by mta5.grp.scd.yahoo.com with SMTP; 11 Jun 2005 01:59:55 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [66.218.69.6] by n15.bulk.scd.yahoo.com with NNFMP; 11 Jun 2005 01:59:55 -0000\r\nReceived: from [66.218.66.88] by mailer6.bulk.scd.yahoo.com with NNFMP; 11 Jun 2005 01:59:53 -0000\r\nX-Sender: mikofski@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 9087 invoked from network); 10 Jun 2005 18:21:46 -0000\r\nReceived: from unknown (66.218.66.166)\n  by m24.grp.scd.yahoo.com with QMQP; 10 Jun 2005 18:21:46 -0000\r\nReceived: from unknown (HELO n4a.bulk.scd.yahoo.com) (66.94.237.38)\n  by mta5.grp.scd.yahoo.com with SMTP; 10 Jun 2005 18:21:46 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [66.218.66.58] by n4.bulk.scd.yahoo.com with NNFMP; 10 Jun 2005 18:21:16 -0000\r\nReceived: from [66.218.66.72] by mailer7.bulk.scd.yahoo.com with NNFMP; 10 Jun 2005 18:21:15 -0000\r\nDate: Fri, 10 Jun 2005 18:21:14 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;d8clmq+ceku@...&gt;\r\nIn-Reply-To: &lt;d5p5vg+9jkd@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 2387\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-system\r\nX-eGroups-Msg-Info: 1:12:0\r\nFrom: &quot;Mark Alexander Mikofski&quot; &lt;mikofski@...&gt;\r\nSubject: Re: ct2ctml problems?  (May not be a Cantera problem, though)\r\nX-Yahoo-Group-Post: member; u=43678362; y=rJu3DqrW_l8Q01x8bnwRlg4Ub52mK2k71uIO17C-gGNgM6aBkQ\r\nX-Yahoo-Profile: bwanamarko\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 11 Jun 2005 01:59:52 -0000\r\n\r\nMark,\n\nI had the exact same problem. If you haven&#39;t already solve yours, \ntry this: Delete the PYTHON_CMD variable you created, and only add \nc:&#92;Python24 to your path.\n\nHope that helps,\nMark\n\n--- In cantera@yahoogroups.com, &quot;markscha&quot; &lt;mschaffer@s...&gt; wrote:\n&gt; Well, just when I was getting productive, I ran into a problem \nwith \n&gt; Cantera/Python.\n&gt; \n&gt; I had Cantera working on this XP workstation, but I was trying to \n&gt; install another Python package (gnuplot-py 1.7) when I realized \nthat \n&gt; I still had an older version of Python installed (2.3), and this \nwas \n&gt; interfering with the gnuplot-py package.  So, I uninstalled the \n2.3 \n&gt; version, removed it from my PATH, and viola---Cantera started \n&gt; complaining:  &quot;...could not convert input file to CTML&quot;.\n&gt; \n&gt; I uninstalled Cantera, Python, Numpy, etc., reboot, re-installed \n&gt; Python, Numpy stuff, and Cantera, and I still get the same thing.\n&gt; \n&gt; I am using Cantera 1.5.5 and Python 2.4, etc. (the standard stuff) \n&gt; on a XP workstation.  \n&gt; \n&gt; So, am I screwed or what?  I have tried to clean my system several \n&gt; times, and I keep getting the same behavior.  I have verified the \n&gt; file pops up in the correct TMP directory.  I have also tried \n&gt; replaciing the PYTHON_CMD and put c:&#92;Python24 in the PATH.  I have \n&gt; left the directories to be the default values, and I have tried \nsome \n&gt; non-defaults.\n&gt; \n&gt; Any thoughts?\n&gt; \n&gt; -----Mark\n&gt; \n&gt; An example Python Traceback follows:\n&gt; \n&gt; Traceback (most recent call last):\n&gt;   File &quot;C:&#92;Documents and Settings&#92;mas&#92;Desktop&#92;Desktop&#92;Cantera2\n&gt; &#92;cantera15&#92;demos&#92;Python&#92;mix1.py&quot;, line 25, in ?\n&gt;     gas_a = Air()\n&gt;   File &quot;C:&#92;Python24&#92;Lib&#92;site-packages&#92;Cantera&#92;gases.py&quot;, line 40, \nin \n&gt; Air\n&gt;     return Solution(src=&quot;air.cti&quot;, id=&quot;air&quot;)\n&gt;   File &quot;C:&#92;Python24&#92;Lib&#92;site-packages&#92;Cantera&#92;solution.py&quot;, line \n38, \n&gt; in __init__\n&gt;     root = XML.XML_Node(name = &#39;doc&#39;, src = src, preprocess = 1)\n&gt;   File &quot;C:&#92;Python24&#92;Lib&#92;site-packages&#92;Cantera&#92;XML.py&quot;, line 35, in \n&gt; __init__\n&gt;     self._xml_id = _cantera.xml_get_XML_File(src)\n&gt; error: \n&gt; \n&gt; ************************************************\n&gt;                 Cantera Error!                  \n&gt; ************************************************\n&gt; \n&gt; \n&gt; Procedure: ct2ctml\n&gt; Error:   could not convert input file to CTML\n&gt;  command line was: c:&#92;python24&#92;python.exe C:&#92;DOCUME~1&#92;mas&#92;LOCALS~1\n&gt; &#92;Temp/.cttmp1115691081.pyw&gt; ct2ctml.log 2&gt;&1\n\n\n\n\n\n"}}